default_stages: [commit, push]
fail_fast: true
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21  # pick the isort version you'd like to use from https://github.com/pre-commit/mirrors-isort/releases
    hooks:
    - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
  - repo: local
    hooks:
      - id: install-pylint
        name: install-pylint
        entry: python -m pip install pylint
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python -m pylint.__main__
        language: system
        types: [python]
